PATHS:
  - vanilla/32
  # - ids/avg
  # - ids/qda
  # - ids/avg_cvae
  # - ids/cvae
  # - ids/qda_cvae
  - ids/gr
  # - vanilla_32/1
  # - ids/avg_cvae_100
  # - ids/qda_cvae_10
  - ids/qda_cvae_p10
  - ids/avg_cvae_p
  - ids/avg_cvae_p10
  - ids/gr_10
  - ids/gr_20
  - ids/qda_cvae_p20

OUT: /mnt/home/jwu10/working/ceph/results/vae/ids/