PATHS:
  - cvae/cvae_32
  - vanilla/32
  - mals/neg
  - mals/pos
  - mals/neg_100
  - mals/neg_1000
  - mals/neg_quad
  - mals/neg_quad_100
  - mals/neg_cub
  - mals/direct
  - mals/direct_100

OUT: /mnt/home/jwu10/working/ceph/results/vae/mals/