# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
name: vae
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.0
  - babel=2.16.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - black=23.9.1
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.2.1
  - cmocean=3.1.3
  - colorama=0.4.6
  - colorcet=3.0.1
  - colorspacious=1.1.2
  - comm=0.1.4
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cython=3.0.0
  - cytoolz=0.12.0
  - dask-core=2023.6.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.5.0
  - faiss=1.6.5
  - faiss-cpu=1.6.5
  - fbpca=1.0
  - ffmpeg=4.2.2
  - fftw=3.3.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.4.0
  - ghp-import=2.1.0
  - giflib=5.2.1
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - griffe=1.1.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.9.0
  - hdf5=1.12.1
  - hdf5storage=0.1.19
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.31.1
  - importlib-metadata=6.0.0
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - ipykernel=6.25.2
  - ipython=8.15.0
  - jedi=0.19.0
  - jinja2=3.1.4
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=4.12.0
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64
  - lerc=3.0
  - libaec=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.2.10
  - libcups=2.4.2
  - libcurand=10.3.3.141
  - libcurl=8.2.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libfaiss=1.6.5
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzopfli=1.0.3
  - line-profiler=4.1.3
  - llvmlite=0.40.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.7
  - markupsafe=2.1.5
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mergedeep=1.3.4
  - mkdocs=1.6.0
  - mkdocs-autorefs=1.1.0
  - mkdocs-gallery=0.10.1
  - mkdocs-gen-files=0.5.0
  - mkdocs-get-deps=0.2.0
  - mkdocs-literate-nav=0.6.1
  - mkdocs-macros-plugin=1.0.5
  - mkdocs-material=9.5.32
  - mkdocs-material-extensions=1.3.1
  - mkdocs-section-index=0.3.9
  - mkdocstrings=0.25.2
  - mkdocstrings-python=1.10.8
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mscorefonts=0.0.1
  - munkres=1.1.4
  - mypy-extensions=1.0.0
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.1
  - nspr=4.35
  - nss=3.89.1
  - numba=0.57.1
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.14
  - opentsne=0.6.2
  - packaging=23.1
  - paginate=0.5.6
  - pandas=2.0.3
  - param=2.0.2
  - parso=0.8.3
  - partd=1.4.0
  - pathspec=0.11.2
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=3.10.0
  - ply=3.11
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - protobuf=5.27.2
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyct=0.5.0
  - pygments=2.16.1
  - pymdown-extensions=10.9
  - pynndescent=0.5.10
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=1.13.1=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7
  - pywavelets=1.5.0
  - pyyaml=6.0
  - pyyaml-env-tag=0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - regex=2024.7.24
  - requests=2.31.0
  - scikit-image=0.19.2
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - sentry-sdk=2.9.0
  - setproctitle=1.3.3
  - setuptools=68.0.0
  - sip=6.6.2
  - six=1.16.0
  - smmap=5.0.1
  - snappy=1.1.9
  - sqlite=3.41.2
  - ssumo=0.1.dev0
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - tbb=2021.8.0
  - termcolor=2.4.0
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.10.0
  - typing_extensions=4.7.1
  - tzdata=2023c
  - umap-learn=0.5.3
  - urllib3=1.26.16
  - wandb=0.17.5
  - watchdog=4.0.2
  - wcwidth=0.2.6
  - wheel=0.38.4
  - x264=1!157.20191217
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
