activation: prelu
arena_size:
- - -400
  - -400
  - -10
- - 400
  - 400
  - 250
base_path: /mnt/home/jwu10/working/behavior_vae/
batch_size: 5000
beta: 20
data_path: /mnt/home/jwu10/working/data/ensemble_healthy/pose_aligned.h5
face_xpos: false
is_diag: false
jpe_scale: 1
kernel_size: 3
lock_weights: false
model_type: "rcnn"
num_epochs: 400
speed_decoder: "avg"
speed_loss_scale: 20
speed_reg_scale: 0
stride: 1
window: 51
z_dim: 128
load_model: /mnt/home/jwu10/working/behavior_vae/results/rc_w51_b20_360_full/
load_epoch: 200