activation: prelu
arena_size:
- - -400
  - -350
  - 10
- - 200
  - 400
  - 200
base_path: /mnt/home/jwu10/working/behavior_vae/
batch_size: 2000
data_path: /mnt/home/jwu10/working/data/ensemble_healthy/pose_aligned.h5
direction_process: "midfwd"
is_diag: false
kernel_size: 3
lock_weights: false
model_type: "rcnn"
invariant: null
num_epochs: 600
speed_decoder: "avg"
stride: 1
window: 51
z_dim: 128
load_model: /mnt/home/jwu10/working/behavior_vae/results/rc_w51_midfwd_full/
load_epoch: 400
loss_scale:
  speed: 20
  rotation: 1
  jpe: 1
  prior: 20
  root: 1