activation: prelu
arena_size: null
base_path: /mnt/home/jwu10/working/behavior_vae/
batch_size: 5000
beta: 20
data_path: /mnt/home/jwu10/working/data/ensemble_healthy/pose_aligned.h5
face_xpos: false
is_diag: false
jpe_scale: 1
kernel_size: 3
lock_weights: false
model_type: "rcnn"
invariant: "direction"
num_epochs: 200
speed_decoder: null
speed_loss_scale: 0
speed_reg_scale: 0
stride: 1
window: 51
z_dim: 128
load_model: /mnt/home/jwu10/working/behavior_vae/results/di_rc_w51_b20_360_full/
load_epoch: 20