activation: prelu
arena_size:
- - -400
  - -350
  - 10
- - 200
  - 400
  - 200
base_path: /mnt/home/jwu10/working/behavior_vae/
batch_size: 2000
data_path: /mnt/home/jwu10/working/data/ensemble_healthy/pose_aligned.h5
face_xpos: false
is_diag: false
kernel_size: 3
lock_weights: false
model_type: "hrcnn"
invariant: null
num_epochs: 200
speed_decoder: null
stride: 1
window: 51
z_dim: 128
load_model: /mnt/home/jwu10/working/behavior_vae/results/hr_w51_b15_midfwd_full_o0/
load_epoch: 196
loss_scale:
  speed_sse: 0
  speed_reg: 0
  rotation: 1
  jpe: 1
  prior: 15
  root: 1
  hier_orthogonal: 0